services:
  # Cloud Backend - Optimized for Render.com (No Puppeteer)
  - type: web
    name: fortai-cloud-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000