services:
  # All-in-One Service - Complete ForTAI with Real Screenshots
  - type: web
    name: fortai-all-in-one
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    rootDir: ./all-in-one